# Generated by Django 4.2.5 on 2023-10-28 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comentarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComentariosManager',
        ),
    ]
