# Generated by Django 4.2.6 on 2023-11-01 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comentarios', '0002_delete_comentariosmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comentarios.comentarios'),
        ),
    ]
